import Control.Exception

main = undefined
-- now there's a try and an exception monad